<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>try-catch</title>
		<script>
			function test(){
				try{
					allert("hello world!");
				}catch(e){
					msg="다음과 같은 오류가 발생함:"+e.massage;
					alert(msg);
					//msg주석으로 넣으면 아예 오류가 안남.
				}finally{
					alert("finally")
					//오류가 있던 없던 그냥 찍어줌
				}
			}
				/*try {
					정상이라면 이 코드는 아무런 문제없이 블록의 시작부터 끝까지 실행된다.
					하지만 경우에 따라 예외가 발생할 수 있다.
				}catch(e){
					이 블록 내부의 문장들은 오직 try블록에서 예외가 발생할 경우에만 실행된다.
					이 문장들에서는 지역변수 e를 사용하여 Error 객체를 발생한다.
				}finally{
					이 블록에서는 try 블록에서 일어난 일에 관계없이 무조건 실행될
					코드가 위치한다.
					이 코드는 try 블록이 어떻게든 종료되면 실행된다.
					try블록이 종료되는 상황은 다음과 같다.
					
					1)정상적으로 블록의 끝에 도달했을때
					2)break, continue 또는 return문에 의해서
					3)예외가 발생했지만 catch절에서 처리했을때
					4)예외가 발생했고 그것이 잡히지 않은채 퍼져나갈때
				}  */
			//test();
				
				
				var random=Math.floor(Math.random()*100)+1;
					console.log(random);
				function guess(){
					//1)랜덤수 추출
					var input=document.getElementById("number").value;
					//2)작성한 number 값 가져오기
					if(random == input){
						document.getElementById("msg").innerHTML="정답입니다.";
					}else if(random>input ){
						document.getElementById("msg").innerHTML="수가 큽니다.";
					}else if(random<input){
						document.getElementById("msg").innerHTML="수가 작습니다.";
					}
					
				}
			
		</script>
	</head>
	<body>
		<h1>Number Guess</h1>
		<p>1부터 100사이의 숫자를 입력하세요</p>
		<input type="text" id= "number">
		<button onclick="guess();">숫자추측</button>
		<p id="msg"></p>
	</body>
</html>